PROJECT 2 : MILESTONE TWO
tanzila-abedin/TheNextWeb-clone pull request #1
Opened 2021-02-25 21:50 UTC by tanzila-abedin

I have forked this project from my previous working partner with whom I have completed this **project, milestone-one.**
This is the other half of the **project, milestone-two.** My current coding partner @JulianaOsemeke and I are working on it.

2021-02-25 22:10 UTC, tanzila-abedin commented
Hello 

@JulianaOsemeke and my project repository do contain GitHub flow action but it refuses to apply it to the pull request to check for linter errors.
We are failing to understand what might be causing it. Kindly advise!

Thank you :)

2021-02-26 00:47 UTC, yocosaka requested changes
# Status: Changes Required♻️ 

### Great job so far, team👍  

You two have made an amazing job🚀
There are some points to improve before you go ahead.
Let's cover a few details together to make your project better😊 

## Required changes:
- [ ] Use meaningful names for your Pull Requests and add a summary of its content as described [here](https://microverse.zendesk.com/hc/en-us/articles/360055660814-Professional-GitHub-repository)
- [ ] Add a descriptive README file to your repositories as described [here](https://microverse.zendesk.com/hc/en-us/articles/360055660814-Professional-GitHub-repository)
- [x] CSS styles would use media queries min-width: "1024px" as the large breakpoint, instead of "1025px"
- [ ] Live demo link is not the latest. Could you refresh it to the latest one?

### Latest news section

- [x] It has only 3 rows, but it would have 4 articles per row in Desktop view
- [x] Images should be the full width of the container in tablet and desktop views

### Categories (Apps, Gear, Tech, etc) section  in each category

- [ ] The first article title (eg. "GameStop stocks hit record high — thanks to Redditors") should be a header(hx) tag and a link (a tag)
- [ ] The second article title (eg. "Alibaba shares jump 8% as Jack Ma surfaces after 3 months") should use a header(hx) tag and a link (a tag)
- [ ] In the rest of the articles, each list should have each link (a tag). Now link tags are included in link(a tag), but link tag(ul/li) and link(a tag) should be used like below.
eg. ` <ul><li><a href="">Article title</a></li></ul>`

### Latest Deals section

- [ ] The link (a tag) to "See all deals" is in the same row that the title but aligned to the right
- [ ] Each article should have a title (hx tag), both of them with a link (a tag)
- [ ] There should be 3 articles per row on a tablet view, and 4 on desktop
- [ ] Images should be the full width of the container in tablet and desktop views
- [ ] This section should have a little margin or padding to the left side of it

## Optional changes [OPTIONAL]
- [ ] [OPTIONAL] You can use `object-fit: cover;` in each image in order to maintain the ratio of images

Please request another review once you are ready👍


### With all my respect 🍀

Yoko Saka

2021-02-26 00:47 UTC, yocosaka commented on index.html
> +              <p><a class="cat-grey-txt"href="#">Ivan Mehta</a><span class="grey-txt">. 1 day ago</span></p>
- [ ] Use lowercase element names: you can see specific description [here](https://www.w3schools.com/html/html5_syntax.asp)
- [ ] Using inline styles is one of the [common mistakes](https://speckyboy.com/good-bad-css-practices). Styles should be defined as separated from html.

2021-02-26 15:56 UTC, tanzila-abedin commented
@yocosaka  Good Day!

We have made the changes you asked for. Kindly have a look!

2021-02-27 06:59 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi, @tanzila-abedin and @JulianaOsemeke, great job on this project :+1: However, I would like to point out some of the missing comments from the previous review which were not addressed. Kindly check the comments below:

- `Latest news` (min-width: 768px)
`Original`
![w](https://user-images.githubusercontent.com/46388113/109378025-29338780-78c7-11eb-8950-57674eff960c.png)
`Clone`
![q](https://user-images.githubusercontent.com/46388113/109378017-1faa1f80-78c7-11eb-8b70-aad206cb0284.png)
- `Categories section` (min-width: 768px)
Elements are to be aligned in 1 column but currently, we have elements aligned in 2 columns. Let us kindy fix this. Kindly compare our clone project to the [original](https://perma.cc/M5ZV-Q2D6) on all screen sizes
`Original`
![e](https://user-images.githubusercontent.com/46388113/109378140-05bd0c80-78c8-11eb-8764-dc751ab61fbd.png)
`Clone`
![r](https://user-images.githubusercontent.com/46388113/109378157-25eccb80-78c8-11eb-83b1-3e0e777a848c.png)
- `Latest deals` (min-width: 768px)
`Original`
![t](https://user-images.githubusercontent.com/46388113/109378200-84b24500-78c8-11eb-8650-1ed6f00c8447.png)
`Clone`
![y](https://user-images.githubusercontent.com/46388113/109378198-7f54fa80-78c8-11eb-95d4-c04fe82c8dee.png)
- README file: In the author section, one of the links to the social handles is not working it is broken. Also, it is not professional to have an Instagram account where it is also a private account, kindly use Twitter instead, where we have our professional profile and it is public

In all the app is not responsive, let us take it section by section and compare our app with the original. Implement the responsive requirements :smile: 

Once this is addressed, kindly submit another code review request :+1: 
_Happy coding_ :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-27 13:37 UTC, tanzila-abedin commented
Hello @addod19 

When we were cloning this website we had followed the dimensions of **Mobile (min-width: 320px ),Tablet (768px) and Laptop(1024px)** given by the Microverse project scope. For each view, they wanted us to style as shown below and not as per the original website.
**Microverse Scope:**
![Screenshot from 2021-02-27 15-19-56](https://user-images.githubusercontent.com/60758407/109388527-55272b00-7910-11eb-8499-15cdb1b31cbd.png)
![Screenshot from 2021-02-27 15-20-01](https://user-images.githubusercontent.com/60758407/109388537-738d2680-7910-11eb-8a61-3570baf9e221.png)
![Screenshot from 2021-02-27 15-20-09](https://user-images.githubusercontent.com/60758407/109388542-7d168e80-7910-11eb-9858-9c9a41e6b7d5.png)

**Here's the SS of the website we cloned:**
Mobile view
![Uploading Screenshot from 2021-02-27 15-14-52.png…]()
Tablet view 
![Screenshot from 2021-02-27 15-13-51](https://user-images.githubusercontent.com/60758407/109388644-0af27980-7911-11eb-92ee-311ba92fde8b.png)
Laptop view 
![Screenshot from 2021-02-27 15-15-36](https://user-images.githubusercontent.com/60758407/109388662-21003a00-7911-11eb-85c6-a69b2c23ee6f.png)

2021-02-27 15:05 UTC, voscarmv approved these changes
# Milestone status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

**[OPTIONAL]**

- The only detail I could notice is that some of your images appear stretched on different display modes. Please take some time to correct this issue:
![image](https://user-images.githubusercontent.com/2739245/109391083-f5625d00-78da-11eb-9b8e-311597a4a348.png)


### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-27 15:13 UTC, merged